# Generated by Django 4.2.1 on 2023-10-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='user',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
